# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import coral_word_pb2 as coral__word__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coral_word_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoralWordServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryWord = channel.unary_unary(
                '/coral_word.CoralWordService/QueryWord',
                request_serializer=coral__word__pb2.WordRequest.SerializeToString,
                response_deserializer=coral__word__pb2.WordDescList.FromString,
                _registered_method=True)


class CoralWordServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoralWordServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryWord': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryWord,
                    request_deserializer=coral__word__pb2.WordRequest.FromString,
                    response_serializer=coral__word__pb2.WordDescList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coral_word.CoralWordService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coral_word.CoralWordService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoralWordService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral_word.CoralWordService/QueryWord',
            coral__word__pb2.WordRequest.SerializeToString,
            coral__word__pb2.WordDescList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LLMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WordDefinitions = channel.unary_unary(
                '/coral_word.LLMService/WordDefinitions',
                request_serializer=coral__word__pb2.WordDefinitionsRequest.SerializeToString,
                response_deserializer=coral__word__pb2.WordDefinitionsResponse.FromString,
                _registered_method=True)
        self.Article = channel.unary_unary(
                '/coral_word.LLMService/Article',
                request_serializer=coral__word__pb2.ArticleRequest.SerializeToString,
                response_deserializer=coral__word__pb2.ArticleResponse.FromString,
                _registered_method=True)


class LLMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WordDefinitions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Article(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WordDefinitions': grpc.unary_unary_rpc_method_handler(
                    servicer.WordDefinitions,
                    request_deserializer=coral__word__pb2.WordDefinitionsRequest.FromString,
                    response_serializer=coral__word__pb2.WordDefinitionsResponse.SerializeToString,
            ),
            'Article': grpc.unary_unary_rpc_method_handler(
                    servicer.Article,
                    request_deserializer=coral__word__pb2.ArticleRequest.FromString,
                    response_serializer=coral__word__pb2.ArticleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coral_word.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coral_word.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WordDefinitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral_word.LLMService/WordDefinitions',
            coral__word__pb2.WordDefinitionsRequest.SerializeToString,
            coral__word__pb2.WordDefinitionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Article(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral_word.LLMService/Article',
            coral__word__pb2.ArticleRequest.SerializeToString,
            coral__word__pb2.ArticleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
