// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: proto/coral_word.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoralWordService_QueryWord_FullMethodName = "/coral_word.CoralWordService/QueryWord"
)

// CoralWordServiceClient is the client API for CoralWordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoralWordServiceClient interface {
	QueryWord(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*WordDescList, error)
}

type coralWordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoralWordServiceClient(cc grpc.ClientConnInterface) CoralWordServiceClient {
	return &coralWordServiceClient{cc}
}

func (c *coralWordServiceClient) QueryWord(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*WordDescList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WordDescList)
	err := c.cc.Invoke(ctx, CoralWordService_QueryWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoralWordServiceServer is the server API for CoralWordService service.
// All implementations must embed UnimplementedCoralWordServiceServer
// for forward compatibility.
type CoralWordServiceServer interface {
	QueryWord(context.Context, *WordRequest) (*WordDescList, error)
	mustEmbedUnimplementedCoralWordServiceServer()
}

// UnimplementedCoralWordServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoralWordServiceServer struct{}

func (UnimplementedCoralWordServiceServer) QueryWord(context.Context, *WordRequest) (*WordDescList, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryWord not implemented")
}
func (UnimplementedCoralWordServiceServer) mustEmbedUnimplementedCoralWordServiceServer() {}
func (UnimplementedCoralWordServiceServer) testEmbeddedByValue()                          {}

// UnsafeCoralWordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoralWordServiceServer will
// result in compilation errors.
type UnsafeCoralWordServiceServer interface {
	mustEmbedUnimplementedCoralWordServiceServer()
}

func RegisterCoralWordServiceServer(s grpc.ServiceRegistrar, srv CoralWordServiceServer) {
	// If the following call panics, it indicates UnimplementedCoralWordServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoralWordService_ServiceDesc, srv)
}

func _CoralWordService_QueryWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoralWordServiceServer).QueryWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoralWordService_QueryWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoralWordServiceServer).QueryWord(ctx, req.(*WordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoralWordService_ServiceDesc is the grpc.ServiceDesc for CoralWordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoralWordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coral_word.CoralWordService",
	HandlerType: (*CoralWordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryWord",
			Handler:    _CoralWordService_QueryWord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coral_word.proto",
}

const (
	LLMService_WordDefinitions_FullMethodName = "/coral_word.LLMService/WordDefinitions"
	LLMService_Article_FullMethodName         = "/coral_word.LLMService/Article"
)

// LLMServiceClient is the client API for LLMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMServiceClient interface {
	WordDefinitions(ctx context.Context, in *WordDefinitionsRequest, opts ...grpc.CallOption) (*WordDefinitionsResponse, error)
	Article(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
}

type lLMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMServiceClient(cc grpc.ClientConnInterface) LLMServiceClient {
	return &lLMServiceClient{cc}
}

func (c *lLMServiceClient) WordDefinitions(ctx context.Context, in *WordDefinitionsRequest, opts ...grpc.CallOption) (*WordDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WordDefinitionsResponse)
	err := c.cc.Invoke(ctx, LLMService_WordDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) Article(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, LLMService_Article_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMServiceServer is the server API for LLMService service.
// All implementations must embed UnimplementedLLMServiceServer
// for forward compatibility.
type LLMServiceServer interface {
	WordDefinitions(context.Context, *WordDefinitionsRequest) (*WordDefinitionsResponse, error)
	Article(context.Context, *ArticleRequest) (*ArticleResponse, error)
	mustEmbedUnimplementedLLMServiceServer()
}

// UnimplementedLLMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMServiceServer struct{}

func (UnimplementedLLMServiceServer) WordDefinitions(context.Context, *WordDefinitionsRequest) (*WordDefinitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WordDefinitions not implemented")
}
func (UnimplementedLLMServiceServer) Article(context.Context, *ArticleRequest) (*ArticleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Article not implemented")
}
func (UnimplementedLLMServiceServer) mustEmbedUnimplementedLLMServiceServer() {}
func (UnimplementedLLMServiceServer) testEmbeddedByValue()                    {}

// UnsafeLLMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMServiceServer will
// result in compilation errors.
type UnsafeLLMServiceServer interface {
	mustEmbedUnimplementedLLMServiceServer()
}

func RegisterLLMServiceServer(s grpc.ServiceRegistrar, srv LLMServiceServer) {
	// If the following call panics, it indicates UnimplementedLLMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMService_ServiceDesc, srv)
}

func _LLMService_WordDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).WordDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_WordDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).WordDefinitions(ctx, req.(*WordDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_Article_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).Article(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_Article_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).Article(ctx, req.(*ArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMService_ServiceDesc is the grpc.ServiceDesc for LLMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coral_word.LLMService",
	HandlerType: (*LLMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WordDefinitions",
			Handler:    _LLMService_WordDefinitions_Handler,
		},
		{
			MethodName: "Article",
			Handler:    _LLMService_Article_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coral_word.proto",
}
